enum ACTION_TYPES {
    STATE_LOAD = "USERS :: STATE LOAD",
    WRITE_TO_STORE_USERS = "USERS :: WRITE TO STORE USERS",
    DELETE_USER = "USERS :: DELETE USER",
    ADD_USERS = "USERS :: ADD USER"
}

export default ACTION_TYPES